# This is a sample ORM CR for Knative CRD.
apiVersion: turbonomic.com/v1alpha1
kind: OperatorResourceMapping
metadata:
  # Knative operator CRD name
  name: knativeservings.operator.knative.dev
spec:
  resourceMappings:
    - srcResourceSpec:
        kind: Deployment
        componentNames:
          - activator
          - autoscaler
          - controller
          - domain-mapping
          - domainmapping-webhook
          - webhook
      resourceMappingTemplates:
        - srcPath: .spec.template.spec.containers[?(@.name=="{{.componentName}}")].resources.limits
          destPath: .spec.resources[?(@.container=="{{.componentName}}")].limits
        - srcPath: .spec.template.spec.containers[?(@.name=="{{.componentName}}")].resources.requests
          destPath: .spec.resources[?(@.container=="{{.componentName}}")].requests
