# This is a sample ORM CR for Grafana CRD.
apiVersion: turbonomic.com/v1alpha1
kind: OperatorResourceMapping
metadata:
  # Grafana operator CRD
  name: grafanas.integreatly.org
spec:
  resourceMappings:
    - srcResourceSpec:
        kind: Deployment
        componentNames:
          - grafana-deployment
      resourceMappingTemplates:
        - srcPath: .spec.template.spec.containers[?(@.name=="grafana")].resources
          destPath: .spec.resources
