# This is a sample ORM CR for Redis Cluster CRD.
apiVersion: turbonomic.com/v1alpha1
kind: OperatorResourceMapping
metadata:
  # Redis Cluster operator CRD
  name: redisenterpriseclusters.app.redislabs.com
spec:
  resourceMappings:
    - srcResourceSpec:
        kind: StatefulSet
        componentNames:
          - redis-enterprise
      resourceMappingTemplates:
        - srcPath: .spec.template.spec.containers[?(@.name=="redis-enterprise-node")].resources
          destPath: .spec.redisEnterpriseNodeResources.resources
        - srcPath: .spec.replicas
          destPath: .spec.nodes
    - srcResourceSpec:
        kind: Deployment
        componentNames:
          - redis-enterprise-services-rigger
      resourceMappingTemplates:
        - srcPath: .spec.template.spec.containers[?(@.name=="services-rigger")].resources
          destPath: .spec.redisEnterpriseServicesRiggerResources.resources
