# This is a sample ORM CR for Kafka CRD.
apiVersion: turbonomic.com/v1alpha1
kind: OperatorResourceMapping
metadata:
  # Kafka operator CRD name
  name: kafkas.kafka.strimzi.io
spec:
  resourceMappings:
    - srcResourceSpec:
        kind: StatefulSet
        componentNames:
          - my-cluster-kafka
      resourceMappingTemplates:
        - srcPath: .spec.template.spec.containers[?(@.name=="{{.componentName}}")].resources
          destPath: .spec.kafka.resources
        - srcPath: .spec.replicas
          destPath: .spec.kafka.replicas
    - srcResourceSpec:
        kind: StatefulSet
        componentNames:
          - my-cluster-zookeeper
      resourceMappingTemplates:
        - srcPath: .spec.template.spec.containers[?(@.name=="{{.componentName}}")].resources
          destPath: .spec.zookeeper.resources
        - srcPath: .spec.replicas
          destPath: .spec.zookeeper.replicas
