# This is a sample ORM CR for Knative CRD.
apiVersion: turbonomic.com/v1alpha1
kind: OperatorResourceMapping
metadata:
  # Knative operator CRD name
  name: knativeventings.operator.knative.dev
spec:
  resourceMappings:
    - srcResourceSpec:
        kind: Deployment
        componentNames:
          - eventing-controller
          - eventing-webhook
          - mt-broker-controller
      resourceMappingTemplates:
        - srcPath: .spec.template.spec.containers[?(@.name=="{{.componentName}}")].resources.limits
          destPath: .spec.resources[?(@.container=="{{.componentName}}")].limits
        - srcPath: .spec.template.spec.containers[?(@.name=="{{.componentName}}")].resources.requests
          destPath: .spec.resources[?(@.container=="{{.componentName}}")].requests
    - srcResourceSpec:
        kind: Deployment
        componentNames:
          - mt-broker-filter
      resourceMappingTemplates:
        - srcPath: .spec.template.spec.containers[?(@.name=="filter")].resources.limits
          destPath: .spec.resources[?(@.container=="filter")].limits
        - srcPath: .spec.template.spec.containers[?(@.name=="filter")].resources.requests
          destPath: .spec.resources[?(@.container=="filter")].requests
    - srcResourceSpec:
        kind: Deployment
        componentNames:
          - mt-broker-ingress
      resourceMappingTemplates:
        - srcPath: .spec.template.spec.containers[?(@.name=="ingress")].resources.limits
          destPath: .spec.resources[?(@.container=="ingress")].limits
        - srcPath: .spec.template.spec.containers[?(@.name=="ingress")].resources.requests
          destPath: .spec.resources[?(@.container=="ingress")].requests
    - srcResourceSpec:
        kind: Deployment
        componentNames:
          - imc-controller
          - sugar-controller
      resourceMappingTemplates:
        - srcPath: .spec.template.spec.containers[?(@.name=="controller")].resources.limits
          destPath: .spec.resources[?(@.container=="controller")].limits
        - srcPath: .spec.template.spec.containers[?(@.name=="controller")].resources.requests
          destPath: .spec.resources[?(@.container=="controller")].requests
    - srcResourceSpec:
        kind: Deployment
        componentNames:
          - imc-dispatcher
          - pingsource-mt-adapter
      resourceMappingTemplates:
        - srcPath: .spec.template.spec.containers[?(@.name=="dispatcher")].resources.limits
          destPath: .spec.resources[?(@.container=="dispatcher")].limits
        - srcPath: .spec.template.spec.containers[?(@.name=="dispatcher")].resources.requests
          destPath: .spec.resources[?(@.container=="dispatcher")].requests
