# This is a sample ORM CR for CouchDB CRD.
apiVersion: turbonomic.com/v1alpha1
kind: OperatorResourceMapping
metadata:
  # CouchDB operator CRD
  name: couchdbclusters.couchdb.databases.cloud.ibm.com
spec:
  resourceMappings:
    - srcResourceSpec:
        kind: StatefulSet
        componentNames:
          - c-default-couchdbcluster-m
      resourceMappingTemplates:
#        - srcPath: .spec.template.spec.containers[?(@.name=="db")].resources.requests.cpu
#          destPath: .spec.cpu
#        - srcPath: .spec.template.spec.containers[?(@.name=="db")].resources.requests.memory
#          destPath: .spec.memory
        - srcPath: .spec.template.spec.containers[?(@.name=="db")].resources
          destPath: .spec.db.resources
        - srcPath: .spec.template.spec.containers[?(@.name=="mgmt")].resources
          destPath: .spec.mgmt.resources
        - srcPath: .spec.template.spec.containers[?(@.name=="search")].resources
          destPath: .spec.search.resources
        - srcPath: .spec.replicas
          destPath: .spec.size
