apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: "2023-03-13T16:59:30Z"
  name: redis-cluster-leader
  namespace: ot-operators
  resourceVersion: "867400"
  uid: 3eb3d430-e931-445a-88ff-effe895fdca2
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: redis-cluster-leader
