# permissions for end users to edit advicemappings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: advicemapping-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: orm
    app.kubernetes.io/part-of: orm
    app.kubernetes.io/managed-by: kustomize
  name: advicemapping-editor-role
rules:
- apiGroups:
  - devops.turbonomic.io
  resources:
  - advicemappings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devops.turbonomic.io
  resources:
  - advicemappings/status
  verbs:
  - get
