# permissions for end users to view operatorresourcemappings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: operatorresourcemapping-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: orm
    app.kubernetes.io/part-of: orm
    app.kubernetes.io/managed-by: kustomize
  name: operatorresourcemapping-viewer-role
rules:
- apiGroups:
  - devops.turbonomic.io
  resources:
  - operatorresourcemappings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - devops.turbonomic.io
  resources:
  - operatorresourcemappings/status
  verbs:
  - get
