---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - devops.turbonomic.io
  resources:
  - advicemappings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devops.turbonomic.io
  resources:
  - advicemappings/finalizers
  verbs:
  - update
- apiGroups:
  - devops.turbonomic.io
  resources:
  - advicemappings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - devops.turbonomic.io
  resources:
  - operatorresourcemappings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devops.turbonomic.io
  resources:
  - operatorresourcemappings/finalizers
  verbs:
  - update
- apiGroups:
  - devops.turbonomic.io
  resources:
  - operatorresourcemappings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - turbonomic.com
  resources:
  - operatorresourcemappings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - turbonomic.com
  resources:
  - operatorresourcemappings/status
  verbs:
  - get
