apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: operatorresourcemappings.turbonomic.com
spec:
  group: turbonomic.com
  names:
    kind: OperatorResourceMapping
    listKind: OperatorResourceMappingList
    plural: operatorresourcemappings
    singular: operatorresourcemapping
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
