# This is an ORM CR for IBM Common Services Operators.
apiVersion: turbonomic.com/v1alpha1
kind: OperatorResourceMapping
metadata:
  name: clusterserviceversions.operators.coreos.com
spec:
  resourceMappings:
  - srcResourceSpec:
      kind: Deployment
      componentNames:
      - ibm-auditlogging-operator
      - ibm-cert-manager-operator
      - ibm-commonui-operator
      - ibm-healthcheck-operator
      - ibm-iam-operator
      - ibm-ingress-nginx-operator
      - ibm-licensing-operator
      - ibm-mongodb-operator
      - ibm-monitoring-exporters-operator
      - ibm-monitoring-prometheus-operator-ext
      - ibm-common-service-operator
      - ibm-management-ingress-operator
      - ibm-namespace-scope-operator
      - ibm-platform-api-operator
      - operand-deployment-lifecycle-manager
    resourceMappingTemplates:
      - srcPath: .spec.template.spec.containers[?(@.name=="{{.componentName}}")].resources
        destPath: .spec.install.spec.deployments[0].spec.template.spec.containers[0].resources
  - srcResourceSpec:
      kind: Deployment
      componentNames:
      - ibm-monitoring-grafana-operator
    resourceMappingTemplates:
      - srcPath: .spec.template.spec.containers[?(@.name=="grafana")].resources
        destPath: .spec.install.spec.deployments[0].spec.template.spec.containers[0].resources
