apiVersion: turbonomic.com/v1alpha1
kind: OperatorResourceMapping
metadata:
  name: certmanagers.operator.ibm.com
  labels:
    component: cpfs
spec:
  resourceMappings:
    - srcResourceSpec:
        kind: Deployment
        componentNames:
          - cert-manager-cainjector
          - cert-manager-controller
          - cert-manager-webhook
          - configmap-watcher
      resourceMappingTemplates:
        - srcPath: .spec.template.spec.containers[?(@.name=="cert-manager-cainjector")].resources
          destPath: .spec.certManagerCAInjector.resources
        - srcPath: .spec.template.spec.containers[?(@.name=="cert-manager-controller")].resources
          destPath: .spec.certManagerController.resources
        - srcPath: .spec.template.spec.containers[?(@.name=="cert-manager-webhook")].resources
          destPath: .spec.certManagerWebhook.resources
        - srcPath: .spec.template.spec.containers[?(@.name=="configmap-watcher")].resources
          destPath: .spec.configMapWatcher.resources
