apiVersion: devops.turbonomic.io/v1alpha1
kind: AdviceMapping
metadata:
  labels:
    app.kubernetes.io/name: advicemapping
    app.kubernetes.io/instance: advicemapping-sample
    app.kubernetes.io/part-of: orm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: orm
  name: advicemapping-sample
spec:
  mappings:
  - advisor:
      name: myadvisor
      path: .spec
    target:
      apiVersion: apps/v1
      kind: Deployment
      name: redis-master
      path: .spec.replicas
status:
  advices:
  - adviceValue:
      replicas: 1
    owner:
      path: .spec.replicas
      apiVersion: apps/v1
      kind: Deployment
      name: redis-master
    target: 
      path: .spec.replicas
      apiVersion: apps/v1
      kind: Deployment
      name: redis-master
