# Instana Agent configuration documented at https://github.com/instana/helm-charts/tree/main/instana-agent#configuration-reference
apiVersion: turbonomic.com/v1alpha1
kind: OperatorResourceMapping
metadata:
  name: agents.instana.io
spec:
  resourceMappings:
    - srcResourceSpec:
        kind: DaemonSet
        componentNames:
          - instana-agent
      resourceMappingTemplates:
#        - srcPath: .spec.template.spec.containers[?(@.name=="{{.componentName}}")].resources
#          destPath: .spec.pod.resources
        - srcPath: .spec.template.spec.containers[?(@.name=="{{.componentName}}")].resources.limits.memory
          destPath: .spec.agent.resources.memLimit
        - srcPath: .spec.template.spec.containers[?(@.name=="{{.componentName}}")].resources.limits.cpu
          destPath: .spec.agent.resources.cpuLimit
        - srcPath: .spec.template.spec.containers[?(@.name=="{{.componentName}}")].resources.requests.memory
          destPath: .spec.agent.resources.memReq
        - srcPath: .spec.template.spec.containers[?(@.name=="{{.componentName}}")].resources.requests.cpu
          destPath: .spec.agent.resources.cpuReq


